# Generated by Django 2.1.7 on 2019-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='refund',
            field=models.FloatField(default=22000),
        ),
    ]
