# Generated by Django 2.1.7 on 2019-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_student_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
