# Generated by Django 2.1.7 on 2019-03-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_student_is_scanned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='refund',
            new_name='spend',
        ),
    ]
