# Generated by Django 2.1.7 on 2019-03-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190327_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='present_meal',
            field=models.IntegerField(default=0),
        ),
    ]
