# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20190322_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(default=999),
        ),
    ]
