# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20190322_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmanager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messmanager',
            name='mess',
            field=models.IntegerField(default=999, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='block',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='student',
            name='mess',
            field=models.IntegerField(default=999),
        ),
    ]
