# Generated by Django 2.1.7 on 2019-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_student_present_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='present_meal',
            field=models.IntegerField(default=3),
        ),
    ]
